// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'defaultfirebaseoptions_have_not_been_configured_for_linux_'
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'defaultfirebaseoptions_are_not_supported_for_this_platform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'aizasycw_edronvsy6vyosk5tskqd1otck6aq1k',
    appId: '1:594079591247:web:90e807b74a3fda1e29733a',
    messagingSenderId: '594079591247',
    projectId: 'hmis-f59bd',
    authDomain: 'hmis-f59bd.firebaseapp.com',
    storageBucket: 'hmis-f59bd.firebasestorage.app',
    measurementId: 'g_sgf0fg7p2y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'aizasyc7q0jn8juqscrtz20xkfil9dh8x8nrmd4',
    appId: '1:594079591247:android:60e8db4b70a0148829733a',
    messagingSenderId: '594079591247',
    projectId: 'hmis-f59bd',
    storageBucket: 'hmis-f59bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'aizasyc05_opnwibrnxbj2dkwtyxlenadxjgsbu',
    appId: '1:594079591247:ios:a4a668140a2ef6f329733a',
    messagingSenderId: '594079591247',
    projectId: 'hmis-f59bd',
    storageBucket: 'hmis-f59bd.firebasestorage.app',
    iosBundleId: 'com.example.hmis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'aizasyc05_opnwibrnxbj2dkwtyxlenadxjgsbu',
    appId: '1:594079591247:ios:a4a668140a2ef6f329733a',
    messagingSenderId: '594079591247',
    projectId: 'hmis-f59bd',
    storageBucket: 'hmis-f59bd.firebasestorage.app',
    iosBundleId: 'com.example.hmis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'aizasycw_edronvsy6vyosk5tskqd1otck6aq1k',
    appId: '1:594079591247:web:fbc46dec9a2f829629733a',
    messagingSenderId: '594079591247',
    projectId: 'hmis-f59bd',
    authDomain: 'hmis-f59bd.firebaseapp.com',
    storageBucket: 'hmis-f59bd.firebasestorage.app',
    measurementId: 'g_1kmkeqym9x',
  );
}
